# Generated by Django 5.2.13 on 2026-04-26 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        ("farms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "db_table": "rules",
            },
        ),
        migrations.CreateModel(
            name="RuleAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("open_valve", "Open Valve"),
                            ("close_valve", "Close Valve"),
                            ("dispense_fertilizer", "Dispense Fertilizer"),
                        ],
                        max_length=30,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("priority", models.IntegerField(default=0)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_actions",
                        to="devices.device",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="rules.rule",
                    ),
                ),
            ],
            options={
                "db_table": "rule_actions",
                "ordering": ["priority"],
            },
        ),
        migrations.CreateModel(
            name="RuleCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("capability_type", models.CharField(max_length=30)),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("lt", "<"),
                            ("lte", "<="),
                            ("gt", ">"),
                            ("gte", ">="),
                            ("eq", "="),
                            ("ne", "!="),
                        ],
                        max_length=5,
                    ),
                ),
                ("threshold_value", models.FloatField()),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="rules.rule",
                    ),
                ),
            ],
            options={
                "db_table": "rule_conditions",
            },
        ),
        migrations.CreateModel(
            name="RuleWeatherConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("max_rain_probability_pct", models.IntegerField(default=70)),
                ("check_hours_ahead", models.IntegerField(default=24)),
                (
                    "rule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_constraint",
                        to="rules.rule",
                    ),
                ),
            ],
            options={
                "db_table": "rule_weather_constraints",
            },
        ),
    ]
