# Generated by Django 5.2.13 on 2026-04-26 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("scientific_name", models.CharField(blank=True, max_length=150)),
                ("optimal_soil_moisture_min", models.FloatField()),
                ("optimal_soil_moisture_max", models.FloatField()),
                ("optimal_temperature_min", models.FloatField()),
                ("optimal_temperature_max", models.FloatField()),
                ("irrigation_water_need_mm_per_day", models.FloatField()),
                ("optimal_ph_min", models.FloatField()),
                ("optimal_ph_max", models.FloatField()),
                ("nitrogen_need_ppm", models.FloatField()),
                ("phosphorus_need_ppm", models.FloatField()),
                ("potassium_need_ppm", models.FloatField()),
                (
                    "frost_sensitivity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        default="medium",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "crops",
            },
        ),
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=300)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("area_hectares", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="farms",
                        to="farms.crop",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_farms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "farms",
            },
        ),
    ]
