# Generated by Django 5.2.13 on 2026-04-26 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceTelemetry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("time", models.DateTimeField()),
                ("battery_level", models.IntegerField(blank=True, null=True)),
                ("rssi", models.IntegerField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "db_table": "device_telemetry",
                "indexes": [
                    models.Index(fields=["device", "-time"], name="idx_telemetry_device_time")
                ],
            },
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("time", models.DateTimeField()),
                (
                    "capability_type",
                    models.CharField(
                        choices=[
                            ("soil_moisture", "Soil Moisture"),
                            ("temperature", "Temperature"),
                            ("humidity", "Humidity"),
                            ("ph_level", "pH Level"),
                            ("nitrogen_level", "Nitrogen Level"),
                            ("phosphorus_level", "Phosphorus Level"),
                            ("potassium_level", "Potassium Level"),
                        ],
                        max_length=30,
                    ),
                ),
                ("value", models.FloatField()),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "db_table": "sensor_readings",
                "indexes": [
                    models.Index(fields=["device", "-time"], name="idx_readings_device_time"),
                    models.Index(
                        fields=["capability_type", "-time"], name="idx_readings_capability_time"
                    ),
                ],
            },
        ),
    ]
