# Generated by Django 5.2.13 on 2026-04-26 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmmembership",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="farms.farm",
            ),
        ),
        migrations.AddField(
            model_name="farmmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="farmmembership",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.role"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="farmmembership",
            unique_together={("user", "farm")},
        ),
    ]
