# Generated by Django 5.2.13 on 2026-04-26 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("device_uid", models.CharField(max_length=100, unique=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("sensor", "Sensor"),
                            ("actuator", "Actuator"),
                            ("combined", "Combined"),
                        ],
                        default="sensor",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        default="offline",
                        max_length=10,
                    ),
                ),
                ("location_description", models.CharField(blank=True, max_length=300)),
                ("installed_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("mqtt_username", models.CharField(blank=True, max_length=100)),
                ("mqtt_password_hash", models.CharField(blank=True, max_length=200)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "db_table": "devices",
            },
        ),
        migrations.CreateModel(
            name="DeviceCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "capability_type",
                    models.CharField(
                        choices=[
                            ("soil_moisture", "Soil Moisture"),
                            ("temperature", "Temperature"),
                            ("humidity", "Humidity"),
                            ("ph_level", "pH Level"),
                            ("nitrogen_level", "Nitrogen Level"),
                            ("phosphorus_level", "Phosphorus Level"),
                            ("potassium_level", "Potassium Level"),
                            ("valve_control", "Valve Control"),
                            ("fertilizer_dispenser", "Fertilizer Dispenser"),
                        ],
                        max_length=30,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capabilities",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "db_table": "device_capabilities",
                "unique_together": {("device", "capability_type")},
            },
        ),
    ]
