# Generated by Django 5.2.13 on 2026-05-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(default='ESP32-Prototip', max_length=50)),
                ('temperature', models.FloatField(verbose_name='Sıcaklık (°C)')),
                ('humidity', models.FloatField(verbose_name='Hava Nemi (%)')),
                ('soil_moisture', models.FloatField(verbose_name='Toprak Nemi (%)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
