# Generated by Django 5.2.13 on 2026-05-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0002_activitylog_systemstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstate',
            name='moisture_threshold',
            field=models.FloatField(default=25.0),
        ),
    ]
