# Generated by Django 5.2.13 on 2026-05-04 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0003_systemstate_moisture_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('location_coord', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_moisture', models.FloatField(default=0.0)),
                ('moisture_threshold', models.FloatField(default=25.0)),
                ('is_irrigating', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='sensordata',
            name='parcel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='visualization.parcel'),
        ),
    ]
