# Generated by Django 5.2.13 on 2026-05-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0005_activitylog_ip_address_activitylog_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='battery_level',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='battery_level',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
