# Generated by Django 5.2.13 on 2026-04-26 12:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        ("rules", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("command_uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("open_valve", "Open Valve"),
                            ("close_valve", "Close Valve"),
                            ("dispense_fertilizer", "Dispense Fertilizer"),
                        ],
                        max_length=30,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("received", "Received"),
                            ("executed", "Executed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[("automatic", "Automatic"), ("manual", "Manual")], max_length=15
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="devices.device",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commands",
                        to="rules.rule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "commands",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("rule__isnull", False), ("user__isnull", True)),
                            models.Q(("rule__isnull", True), ("user__isnull", False)),
                            _connector="OR",
                        ),
                        name="commands_either_rule_or_user",
                    )
                ],
            },
        ),
    ]
