# Generated by Django 5.2.13 on 2026-04-26 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FertilizationRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "nutrient_type",
                    models.CharField(
                        choices=[
                            ("nitrogen", "Nitrogen"),
                            ("phosphorus", "Phosphorus"),
                            ("potassium", "Potassium"),
                            ("ph", "pH"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[("scheduled", "Scheduled"), ("urgent", "Urgent")],
                        default="scheduled",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reasoning", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fertilization_recommendations",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "db_table": "fertilization_recommendations",
            },
        ),
        migrations.CreateModel(
            name="FertilizationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "nutrient_type",
                    models.CharField(
                        choices=[
                            ("nitrogen", "Nitrogen"),
                            ("phosphorus", "Phosphorus"),
                            ("potassium", "Potassium"),
                            ("ph", "pH"),
                        ],
                        max_length=15,
                    ),
                ),
                ("product_name", models.CharField(blank=True, max_length=200)),
                ("volume_applied", models.FloatField(blank=True, null=True)),
                ("applied_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fertilization_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fertilization_history",
                        to="farms.farm",
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_entries",
                        to="fertilization.fertilizationrecommendation",
                    ),
                ),
            ],
            options={
                "db_table": "fertilization_history",
            },
        ),
    ]
