# Generated by Django 5.2.13 on 2026-04-26 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("forecast_data", models.JSONField()),
                ("valid_until", models.DateTimeField()),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_cache",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "db_table": "weather_cache",
            },
        ),
    ]
